// app/layout.tsx
import '../styles/globals.css';
import { ReactNode } from 'react';
import ThemeProvider from '../components/ThemeProvider'; // клиентский компонент

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
