// app/layout.tsx
'use client' // нужен для использования useState и useEffect

import '../styles/globals.css';
import { ReactNode, useEffect, useState } from 'react'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<'light' | 'dark'>('light')

  // Можно сохранять выбор в localStorage
  useEffect(() => {
    const saved = localStorage.getItem('theme') as 'light' | 'dark' | null
    if (saved) setTheme(saved)
  }, [])

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark')
    localStorage.setItem('theme', theme)
  }, [theme])

  return (
    <html lang="en">
      <body className="bg-white text-black dark:bg-gray-900 dark:text-white transition-colors duration-300">
        {/* Передаем setTheme в children через контекст или пропсы, если нужно */}
        {children}
      </body>
    </html>
  )
}
